services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibe_call
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # Host 5433 → Container 5432

  # Redis
  redis:
    image: redis:7-alpine
    container_name: auth-redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"   # Host 6380 → Container 6379 for local access

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: auth-rabbitmq
    restart: always
    ports:
      - "5673:5672"    # Host 5673 → Container 5672
      - "15673:15672"  # Host 15673 → Container 15672 (management UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  redis_data:
  rabbitmq_data:
